name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  buildX:
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get tags
        run: git fetch --tags origin
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Logs
        run: git log -n 10 > foobar.txt
      - name: Cat Logs
        run: cat foobar.txt
      - name: Last Release
        run: git describe --tags
      - name: Last Release 2
        run: git describe --tags ${{ github.ref_name }}^
      - name: ReleaseNotes
        run: git log $(git describe --tags ${{github.ref_name}}^)..HEAD --pretty=format:'%h - %s' > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
#          body: "Automatic Release..."
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            Release.txt
            ${{ github.workspace }}-CHANGELOG.txt
            LICENSE